name: Deploy Forester site to Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache OPAM directory
        uses: actions/cache@v3
        with:
          path: ~/.opam
          key: ${{ runner.os }}-opam-forester-${{ hashFiles('**/*opam') }}
          restore-keys: |
            ${{ runner.os }}-opam-forester-

      - name: Install OCaml + Forester
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y opam
          opam init -y --bare
          opam switch create . ocaml-base-compiler.5.1.0 -y || opam switch import . || true
          eval $(opam env)
          opam install forester -y

      - name: Build site
        run: |
          eval $(opam env)
          forester build forest.toml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output   # your build output folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
